interface ApiConfig {
  prodDomain: string;
  devDomain: string;
  prodWsDomain: string;
  devWsDomain: string;
  checkCode: string;
  login: string;
  register: string;
  getSysSetting: string;
  loadMyGroup: string;
  saveGroup: string;
  getGroupInfo: string;
  getGroupInfo4Chat: string;
  dissolutionGroup: string;
  leaveGroup: string;
  addOrRemoveGroupUser: string;
  search: string;
  applyAdd: string;
  loadApply: string;
  dealWithApply: string;
  loadContact: string;
  getContactUserInfo: string;
  addContact2BlackList: string;
  delContact: string;
  getContactInfo: string;
  saveUserInfo: string;
  getUserInfo: string;
  updatePassword: string;
  logout: string;
  sendMessage: string;
  uploadFile: string;
  loadAdminAccount: string;
  updateUserStatus: string;
  forceOffLine: string;
  loadGroup: string;
  adminDissolutionGroup: string;
  saveSysSetting: string;
  getSysSetting4Admin: string;
  loadUpdateDataList: string;
  delUpdate: string;
  saveUpdate: string;
  postUpdate: string;
  loadBeautyAccount: string;
  saveBeautAccount: string;
  delBeautAccount: string;
  checkVersion: string;
}

const api: ApiConfig = {
  prodDomain: "http://127.0.0.1:5050",
  devDomain: "http://127.0.0.1:5050",
  prodWsDomain: "ws://127.0.0.1:5051/ws",
  devWsDomain: "ws://127.0.0.1:5051/ws",
  checkCode: "/account/checkCode",
  login: "/account/login",
  register: "/account/register",
  getSysSetting: "/account/getSysSetting",
  loadMyGroup: "/group/loadMyGroup",
  saveGroup: "/group/saveGroup",
  getGroupInfo: "/group/getGroupInfo",
  getGroupInfo4Chat: "/group/getGroupInfo4Chat",
  dissolutionGroup: "/group/dissolutionGroup",
  leaveGroup: "/group/leaveGroup",
  addOrRemoveGroupUser: "/group/addOrRemoveGroupUser",
  search: "/contact/search",
  applyAdd: "/contact/applyAdd",
  loadApply: "/contact/loadApply",
  dealWithApply: "/contact/dealWithApply",
  loadContact: "/contact/loadContact",
  getContactUserInfo: "/contact/getContactUserInfo",
  addContact2BlackList: "/contact/addContact2BlackList",
  delContact: "/contact/delContact",
  getContactInfo: "/contact/getContactInfo",
  saveUserInfo: "/userInfo/saveUserInfo",
  getUserInfo: "/userInfo/getUserInfo",
  updatePassword: "/userInfo/updatePassword",
  logout: "/userInfo/logout",
  sendMessage: "/chat/sendMessage",
  uploadFile: "/chat/uploadFile",
  loadAdminAccount: "/admin/loadUser",
  updateUserStatus: "/admin/updateUserStatus",
  forceOffLine: "/admin/forceOffLine",
  loadGroup: "/admin/loadGroup",
  adminDissolutionGroup: "/admin/dissolutionGroup",
  saveSysSetting: "/admin/saveSysSetting",
  getSysSetting4Admin: "/admin/getSysSetting",
  loadUpdateDataList: '/admin/loadUpdateList',
  delUpdate: '/admin/delUpdate',
  saveUpdate: "/admin/saveUpdate",
  postUpdate: "/admin/postUpdate",
  loadBeautyAccount: "/admin/loadBeautyAccountList",
  saveBeautAccount: "/admin/saveBeautAccount",
  delBeautAccount: "/admin/delBeautAccount",
  checkVersion: "/update/checkVersion",
};

export default api;
